chicagopython/buddy_mentorship

CHANGELOG.md, CONTRIBUTE.md
=> Add changelog and contribution md files

Pipfile, Pipfile.lock, apps/users/templates/users/login.html, apps/users/templates/users/logout.html, apps/users/tests.py, apps/users/urls.py, buddy_mentorship/settings/local.py, buddy_mentorship/templates/buddy_mentorship/home.html, buddy_mentorship/urls.py, buddy_mentorship/views.py
Create a basic login and logout page
=> Login page

Pipfile, Pipfile.lock, buddy_mentorship/settings/local.py, buddy_mentorship/static/css/app.css, buddy_mentorship/templates/buddy_mentorship/base.html, buddy_mentorship/templates/buddy_mentorship/home.html
Just wanted to get a basic layout in there. Open to changing the style from this for sure.
=> Add django bootstrap and base.html with nav menu and basic layout

apps/users/templates/users/request.html, apps/users/templates/users/requests.html, apps/users/urls.py, apps/users/views.py
Closes #11 
This PR creates buddy request views with dummy data. We will need to spiff them up a bit and have them get actual data once we have the request model
=> basic request views

apps/users/templates/users/login.html, apps/users/templates/users/logout.html, apps/users/templates/users/request.html, apps/users/templates/users/requests.html
=> login, logout, request & requests templates now extend base

CONTRIBUTING.MD, buddy_mentorship/static/css/app.css, buddy_mentorship/static/js/map.js, buddy_mentorship/templates/buddy_mentorship/base.html, buddy_mentorship/templates/buddy_mentorship/profile.html, buddy_mentorship/urls.py, buddy_mentorship/views.py
=> Create Profile Template

buddy_mentorship/tests.py, buddy_mentorship/urls.py
Mucked up merge conflicts on last push - sorry. This pull request fixes those issues.
=> bug fixes: missing urls comma, imports

apps/users/templates/users/request.html, buddy_mentorship/templates/buddy_mentorship/base.html, buddy_mentorship/templates/buddy_mentorship/profile.html, buddy_mentorship/tests.py, buddy_mentorship/views.py
Added form for sending requests with custom messages.
=> Custom messages in buddy requests

buddy_mentorship/forms.py, buddy_mentorship/settings/local.py, buddy_mentorship/settings/production.py, buddy_mentorship/templates/buddy_mentorship/edit_profile.html, buddy_mentorship/tests.py, buddy_mentorship/urls.py, buddy_mentorship/views.py
closes #38 
This PR creates a page which allows new users to edit their information and create a profile
=> Create form to edit user and create profile

buddy_mentorship/settings/local.py, buddy_mentorship/static/css/app.css, buddy_mentorship/templates/buddy_mentorship/base.html, buddy_mentorship/templates/buddy_mentorship/home.html
Adds content and style to the main page, including a short welcome blurb, a "how does this work" section, and a FAQ section.
=> Update footer; add homepage content/style

buddy_mentorship/templates/buddy_mentorship/base.html
Closes #51, does not reinvent wheel. Also changed "BuddyMentorship" in top left of navbar to "ChiPy Mentorship"
=> added contact link + changed app name in nav

buddy_mentorship/templates/buddy_mentorship/search.html, buddy_mentorship/tests.py, buddy_mentorship/views.py
=> add mentee search

apps/users/tests.py, apps/users/urls.py, apps/users/views.py
Closes #77 
Redirect to the github login page
=> redirect to github

buddy_mentorship/tests.py, buddy_mentorship/urls.py, buddy_mentorship/views.py
=> make skill search case insensitive

apps/users/templates/users/request.html, apps/users/views.py, buddy_mentorship/templates/buddy_mentorship/coming_soon.html, buddy_mentorship/templates/buddy_mentorship/experience_form.html, buddy_mentorship/templates/buddy_mentorship/home.html, buddy_mentorship/templates/buddy_mentorship/profile.html, buddy_mentorship/templates/buddy_mentorship/search.html
Closes #98 and closes #99. Also removes the "xxx" from homepage.
=> template cleanup

buddy_mentorship/models.py, buddy_mentorship/templates/buddy_mentorship/profile.html, buddy_mentorship/tests.py, buddy_mentorship/views.py
=> show users offers/requests they have made when viewing a profile

buddy_mentorship/models.py, buddy_mentorship/tests.py
=> remove buddy and change subject

buddy_mentorship/templates/buddy_mentorship/base.html
=> made ChiPy mentorship name in nav bar link to home

buddy_mentorship/templates/buddy_mentorship/search.html
Added search type parameter to navigation links. Closes #132.
=> fix page navigation in search

buddy_mentorship/models.py, buddy_mentorship/tests.py, buddy_mentorship/views.py
=> let users view profiles without creating own

CONTRIBUTE.md, buddy_mentorship/templates/buddy_mentorship/base.html, buddy_mentorship/templates/buddy_mentorship/release_notes.html, buddy_mentorship/urls.py
closes #119 
This PR creates a static release notes page that we should keep up to date we merge new features
=> add release notes page

buddy_mentorship/templates/buddy_mentorship/search.html, buddy_mentorship/tests.py, buddy_mentorship/views.py
Missed a piece of #103 in my last pull request.
=> Add alerts to search if not actively looking for mentors/mentees

buddy_mentorship/templates/buddy_mentorship/profile.html, buddy_mentorship/templates/buddy_mentorship/release_notes.html
=> added descriptive templates for requests
